services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery-server:
    image: eclipse-temurin:21-jre
    volumes: ["./discovery-server:/app"]
    command: ["sh","-c","echo 'discovery stub'"]
    ports: ["8761:8761"]

  config-server:
    image: eclipse-temurin:21-jre
    volumes: ["./config-server:/app"]
    command: ["sh","-c","echo 'config stub'"]
    ports: ["8888:8888"]

  mysql-auth:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: authdb

  mysql-user:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: userdb

  mysql-product:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: productdb

  mysql-cart:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: cartdb


  mysql-order:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: orderdb

  mysql-payment:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: paymentdb

  mysql-notification:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: notificationdb

  mysql-inventory:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Thenu@5612
      MYSQL_DATABASE: inventorydb

  auth-service:
    build: ./auth-service
    ports: ["8081:8081"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-auth:3306/authdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-auth, redis, kafka]

  user-service:
    build: ./user-service
    ports: ["8082:8082"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-user:3306/userdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-user]

  product-service:
    build: ./product-service
    ports: ["8083:8083"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-product:3306/productdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-product, redis]

  cart-service:
    build: ./cart-service
    ports: ["8084:8084"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-cart:3306/cartdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-cart]


  order-service:
    build: ./order-service
    ports: ["8085:8085"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-order:3306/orderdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-order, kafka]

  payment-service:
    build: ./payment-service
    ports: ["8086:8086"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-payment:3306/paymentdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-payment, kafka]

  notification-service:
    build: ./notification-service
    ports: ["8087:8087"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-notification:3306/notificationdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-notification, kafka]

  inventory-service:
    build: ./inventory-service
    ports: ["8088:8088"]
    environment:
      MYSQL_URL: jdbc:mysql://mysql-inventory:3306/inventorydb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Thenu@5612
    depends_on: [mysql-inventory]

  api-gateway:
    image: eclipse-temurin:21-jre
    volumes: ["./api-gateway:/app"]
    command: ["sh","-c","echo 'gateway stub'"]
    ports: ["8080:8080"]
