spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/inventorydb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Passcode123}
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
